version: '3'
services:
  django:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    command: python manage.py runserver 0.0.0.0:8080
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /tmp/app/mysqld:/run/mysqld
    networks:
      - mynetwork

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3308:3306"
    expose:
      - "3306"
      - "3308"
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_DATABASE=sayakat
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
      - MYSQL_ROOT_PASSWORD=mypassword
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql-logs:/var/log/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    networks:
      - mynetwork

networks:
  mynetwork: